config/routes.rb
Rails.application.routes.draw do
  get 'about/index'

  devise_for :users, :controllers => {
    :sessions => 'sessions'
  }
  resources :feeds
  root 'feeds#index'
end

app/models/feed.rb
class Feed < ActiveRecord::Base
  after_validation :get_rss, if: ->(feed){ feed.errors.empty? }

  has_many :items, dependent: :destroy

  validates :url, presence: true, uniqueness: true

  def update_items!
    feed = Feedjira::Feed.fetch_and_parse(self.url)

    return failed_fetch_feed unless feed.respond_to?(:entries)

    feed.entries.each do |entry|
      unless items.where(url: entry.url).exists?
        items.create!({body: entry.content || entry.summary, title: entry.title, url: entry.url, posted_at: entry.published})
        logger.info "created! #{{body: entry.content, title: entry.title, url: entry.url, posted_at: entry.published}.inspect}"
      end
    end
  end

  private

  def get_rss
    feed = Feedjira::Feed.fetch_and_parse(self.url)

    return failed_fetch_feed unless feed.respond_to?(:entries)

    feed.entries.each do |entry|
      self.items.build({body: entry.content || entry.summary, title: entry.title, url: entry.url, posted_at: entry.published})
    end

    self.title = feed.title
  end

  def failed_fetch_feed
    logger.error "failed fetch feed: #{self.url}"
    errors.add(:base, I18n.t('errors.messages.failed_fetch_feed'))
  end
end

app/models/item.rb
class Item < ActiveRecord::Base
  belongs_to :feed

  paginates_per 30
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable,
         :rememberable, :trackable, :validatable
end

app/controllers/about_controller.rb
class AboutController < ApplicationController
  def index
    @feeds = Feed.all
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/feeds_controller.rb
class FeedsController < ApplicationController
  before_action :accessible_check, :except => [:index, :show]

  def index
    last_updated_times = Item.group(:feed_id).maximum(:updated_at)

    @feeds = Feed.all.order(:author).map { |feed|
      { id:         feed.id,
        title:      feed.title,
        author:     feed.author,
        posted_at:  last_updated_times[feed.id]
      }
    }
    feed_ids = params[:id] ? params[:id] : @feeds.map {|f| f[:id]}
    @items = Item.includes(:feed).where(feeds: {id: feed_ids}).order('posted_at desc').page(params[:page])
  end

  def new
    @feed = Feed.new
    @feeds = Feed.all
  end

  def create
    @feed = Feed.new(feed_params)

    if @feed.save
      redirect_to feeds_path
    else
      @feeds = Feed.all
      render :new
    end
  end

  def show
    @feed = Feed.find(params[:id])
    @items = @feed.items
    @feeds = Feed.all
  end

  def edit
    @feed = Feed.find(params[:id])
    @feeds = Feed.all
  end

  def update
    @feed = Feed.find(params[:id])
    @feed.attributes = feed_params

    if @feed.save
      redirect_to feeds_path
    else
      render :edit
    end
  end

  def destroy
    @feed = Feed.destroy(params[:id])
    redirect_to feeds_path
  end

  private

  def feed_params
    params.require(:feed).permit(
      :body, :title, :url, :author, :posted_at
    )
  end

  def accessible_check
    raise unless user_signed_in?
  end

end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController

  before_action :get_feeds

  def new
    super
  end

  def create
    super
  end

  private
  def get_feeds
    @feeds = Feed.all
    @items = Item.includes(:feed).order('posted_at desc').page(params[:page])
  end

end

app/controllers/sessions_controller.rb
class SessionsController < Devise::SessionsController

  before_action :get_feeds

  def new
    super
  end

  def create
    super
  end

  private
  def get_feeds
    @feeds = Feed.all
    @items = Item.includes(:feed).order('posted_at desc').page(params[:page])
  end

end

app/helpers/about_helper.rb
module AboutHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/feeds_helper.rb
module FeedsHelper
end

app/views/about/index.html.haml
%h1 about yochiyochi yomyom
%p よちよち.rbのメンバーのブログを一覧できるところがあればうれしいなと思ってつくりました。
%hr

%h2 how to add new blog
%p 現在、自由にブログを追加することができません。
%p
  ブログURLを
  %a{:href => "https://www.twitter.com/katorie", :target => "_blank"}> @katorie
  までご連絡ください。
%hr

%h2 what is よちよち.rb
%p 毎週月曜日の夜20時〜22時に東京都内のどこかで活動している、初心者による初心者のためのコミュニティです。
%p おもにRuby on Railsとその周辺の技術について学んでいます。
%p プログラミング経験2年以内の方を対象としておりますので、ご注意ください。
%p
  主催者は 
  %a{:href => "https://www.twitter.com/yucao25hours", :target => "_blank"}> @yucao24hours
  (ゆかおさん)です。
%p
  詳しくは、
  %a{:href => "https://www.facebook.com/groups/576966389063750/", :target => "_blank"}> Facebookグループ
  か、
  %a{:href => "http://yochiyochirb.doorkeeper.jp/", :target => "_blank"}> Doorkeeper
  などをチェックしてみてください。
%hr

%h2 fork me on GitHub!
%p yochiyochi yomyomのソースコードはGitHubで管理しています。
%p
  %a{:href => "https://www.twitter.com/katorie", :target => "_blank"}> @katorie
  が
  %a{:href => "https://www.facebook.com/groups/113145785502645/", :target => "_blank"}> RailsGirlsTokyo,more!
  という勉強会でコーチに教えていただきながらつくりました。まだまだ
  %a{:href => "https://github.com/katorie/rss_reader", :target => "_blank"}> 開発途中
  です。

app/views/feeds/create.html.haml
%h1 Feeds#create
%p Find me in app/views/feeds/create.html.erb

app/views/feeds/edit.html.haml
= form_for @feed do |f|
  = f.label :url
  = f.text_field :url
  = f.label :author
  = f.text_field :author
  = f.submit
= link_to "キャンセル", feeds_path

app/views/feeds/index.html.haml
%side
  %h2 following site...
  - @feeds.each do |feed|
    .panel.panel-default
      .panel-heading
        %h3.panel-title= "#{feed[:title]} by #{feed[:author]}"
      .panel-body
        %h5= "Last Updated: #{feed[:posted_at]}"
        -if user_signed_in?
          = link_to "delete", feed_path(feed), method: :delete
          = link_to "edit", edit_feed_path(feed[:id])

%main
  %h2 read items...
  - @items.each do |item|
    .panel.panel-warning
      .panel-heading
        %h3.panel-title= "#{item.feed.title} by #{item.feed.author}"
      .panel-body
        %h4= item.title
        %p= strip_tags(item.body.to_s.truncate(200))
        = link_to "もとを見る", item.url, target: "_blank", class: 'btn btn-primary btn-sm'

  = paginate @items

app/views/feeds/new.html.haml
%h2 add new site?
%br
%h4 please input RSS feed URL and Author

= form_for @feed do |f|
  - if @feed.errors.any?
    %div{:class => "alert alert-danger"}
      %ul
        - @feed.errors.full_messages.each do |msg|
          %li= msg

  %div{:class => "form-group"}
    = f.text_field :url,    :class => "form-control input-lg", :placeholder => 'ex: http://example.com/blog/rss'
    = f.text_field :author, :class => "form-control input-lg", :placeholder => 'ex: Alice or @alice1234'
  = f.submit "add", :class => "btn btn-primary"
  %button{:type => "button", :class => "btn btn-primary"}= link_to "cancel", feeds_path

app/views/feeds/show.html.haml
%h2= "#{@feed.title} by #{@feed.author}"
%hr
-@items.each do |item|
  .panel.panel-warning
    .panel-heading
      %h3.panel-title= item.title
    .panel-body
      %p= strip_tags(item.body.to_s.truncate(200))
    %p.text-right
      = link_to "もとを見る", item.url, target: "_blank"

= link_to "もどる", feeds_path

app/views/feeds/update.html.haml
%h1 Feeds#update
%p Find me in app/views/feeds/update.html.erb

app/views/layouts/application.html.haml
!!!
%html
  %head
    = stylesheet_link_tag "application", :media => "all"
    = csrf_meta_tags
    = favicon_link_tag 'favicon.ico'
    %title yochiyochi yomyom
  %body
    .navbar.navbar-default
      .navbar-header
        %button.navbar-toggle{"data-target" => ".navbar-responsive-collapse", "data-toggle" => "collapse", type: "button"}
          %span.icon-bar
          %span.icon-bar
          %span.icon-bar
        = link_to 'yochiyochi yomyom', root_path, class: 'navbar-brand'
      .navbar-collapse.collapse.navbar-responsive-collapse
        %ul.nav.navbar-nav
          %li
            = link_to 'add new site', new_feed_path if user_signed_in?
          %li.dropdown
            %a.dropdown-toggle{"data-toggle" => "dropdown", href: "#"}
              select site
              %b.caret
            %ul.dropdown-menu
              %li
                - @feeds.each do |feed|
                  = link_to feed[:title], feed
        %ul.nav.navbar-nav.navbar-right
          %li
            = link_to 'about', about_index_path
          %li
            - if user_signed_in?
              = link_to('Logout', destroy_user_session_path, :method => :delete)
            - else
              = link_to('Login', new_user_session_path)

    - if notice
      %p.alert.alert-success= notice
    - if alert
      %p.alert.alert-danger= alert

    = yield

    = javascript_include_tag "application"